name: '🚀 Publish'

on:
  push:
    branches:
      - main

jobs:
  release:
    name: '🚀 Publish'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 23.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: 🚀 Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
